[package]
name = "mdrun"
version = "0.1.1"
edition = "2024"
description = "Markdown notebook runner."
license = "ISC"
readme = "README.md"
repository = "https://github.com/ctsrc/mdrun"
authors = ["Erik Nordstrøm <erik@nordstroem.no>"]
keywords = ["markdown", "commonmark"]

[dependencies]
clap = "4.6.7"
comrak = "0.55.0"
